__author__ = 'thath'

MAJOR_OFFENSE_TYPES = [
    'Aggravated Assault',
    'Arson',
    'Assault, Simple',
    'Burglary',
    'Curfew',
    'Disorderly Conduct',
    'Drugs',
    'DUII',
    'Embezzlement',
    'Forgery',
    'Fraud',
    'Gambling',
    'Homicide',
    'Kidnap',
    'Larceny',
    'Liquor Laws',
    'Motor Vehicle Theft',
    'Offenses Against Family',
    'Prostitution',
    'Rape',
    'Robbery',
    'Runaway',
    'Sex Offenses',
    'Stolen Property',
    'Trespass',
    'Vandalism',
    'Weapons',
]
